import fs from 'fs'
import fp from 'path'
import _ from 'lodash'
import esbuild from 'esbuild'

import packageJSON from './package.json' with { type: 'json' }

const rules = fs.readdirSync('./rules', { withFileTypes: true })
	.filter(file => !/\.test\.((c|m)?(j|t)sx?)$/.test(file.name))
	.map(file => ({
		name: fp.basename(file.name, fp.extname(file.name)),
		path: file.parentPath + '/' + file.name
	}))

const hint = 'Do not modify this file directly as it is auto-generated by `npm run build` command'

{
	const fileName = 'index.js'
	const fileText = `
module.exports = {
	meta: {
		name: '${packageJSON.name}',
	},
	rules: {
		${rules.map(({ name, path }) => `'${name}': require('${path}').default`).join(',\n		')}
	}
}
`.trim()

	fs.writeFileSync(fileName, fileText, { encoding: 'utf-8', flush: true })

	await esbuild.build({
		entryPoints: [fileName],
		outfile: fileName,
		allowOverwrite: true,
		platform: 'node',
		target: 'node22',
		format: 'cjs',
		bundle: true,
		packages: 'external',
		banner: {
			js: '// ' + hint
		},
	})

	// Sanity check
	const plugin = await import('./' + fileName).then(module => module.default)
	if (
		!plugin.rules ||
		Object.keys(plugin.rules).length === 0 ||
		Object.values(plugin.rules).some(rule => typeof rule !== 'object' || typeof rule.create !== 'function')
	) {
		throw new Error('Unexpected an invalid ESLint plugin shape.')
	}

	console.log(fileName)
}

{
	const fileName = 'README.md'
	const fileText = [
		`<!-- ${hint} -->`,
		'',
		'Note that 🔧 indicates the rule is [auto-fixable](https://eslint.org/docs/latest/use/command-line-interface#--fix).',
		'',
		'|Rule|Description|',
		'|---|---|',
		...await Promise.all(rules.map(async ({ name, path }) => {
			const { default: rule } = await import(path)

			return [
				'',
				('`' + name + '` ' + (_.get(rule, 'meta.fixable') ? '🔧' : '')).trim(),
				rule.meta.docs.description,
				''
			].join('|')
		}))
	].join('\n')

	fs.writeFileSync(fileName, fileText, { encoding: 'utf-8', flush: true })

	console.log(fileName)
}